name: Python Application CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pip' # Cache dependencies to speed up future runs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f FAST_API_DIR/requirements.txt ]; then pip install -r FAST_API_DIR/requirements.txt; fi
