name: Python Application CI with AWS

on:
  push:
    branches: [ main, develop ,master]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.9"

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for DVC

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
           ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install DVC and AWS S3
      run: |
        # Install DVC with S3 support for remote storage operations
        pip install dvc[s3] 

    - name: Pull DVC data and run pipeline
      env:
        # Securely access DAGsHub Personal Access Token from GitHub Secrets
        DAGSHUB_PAT: ${{ secrets.DAGSHUB_KEY }}
        # Securely access AWS credentials and region from GitHub Secrets
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        # Pull data and models managed by DVC from remote storage
        dvc pull
        # Run the DVC pipeline, which includes data processing and model training
        dvc repro
